#!/bin/sh

clara_decode=4.3.12
# clara_decode=4.3.11

clara_cook=4.3.12

coatjava_decode=6.5.6
# coatjava_decode=6c.5.4
# coatjava_decode=6b.5.1
# coatjava_decode=6b.4.0

coatjava_cook=6.5.8
# coatjava_cook=6c.5.7
# coatjava_cook=6c.5.4
# coatjava_cook=6b.5.2
# coatjava_cook=6b.5.1
#coatjava_cook=6b.4.1


# for rnum in {011080..011092}
# for rnum in {011143,011144,011145,011155,011156}
# for rnum in {011157,011158,011159,011160,011162}
# for rnum in {011168,011169,011170}
# for rnum in {011163,011165,011171}
# for rnum in {011174..011180}
# for rnum in {011182,011183,011188,011189}
# for rnum in {011190,011191,011193,011194,011197,011198,011199}
# for rnum in {011206,011207,011210,011211,011212,011213,011214,011215,011218,011220,011221,011222,011223,011224}
# for rnum in 011230
# for rnum in {011225,011226,011231,011232,011233,011234,011235,011238,011239}
# for rnum in {011241,011242,011247,011248}
# for rnum in {011250,011251,011252,011253,011254,011256,011257,011258}
# for rnum in {011263,011265,011266,011268}
# for rnum in {011269,011270,011271,011272}
# for rnum in {011273,011274,011276,011277,011279,011282,011283,011284}
# for rnum in 011289 # <=100
# for rnum in 011290 # <=1000
# for rnum in {011291,011292,011293,011294} # <=100
# for rnum in {011295,011296} #all files
# for rnum in {011297,011298,011299} #<=10
# for rnum in 011300 #<=10
# for rnum in 011301  #all files
# for rnum in 011302  #all files
# for rnum in {011307,011308} #all files
#  for rnum in 011309 #all files

# for rnum in {011324..011330}
# for rnum in 011333
# for rnum in 011334
# for rnum in {011336,011338,011339,011340,011341,011342,011345,011346,011347,011348,011351,011352,011354,011356,011357,011358}
# for rnum in {011361,011330,011329,011325,011324}
# for rnum in {011362..011368}
# for rnum in 011372
# for rnum in {011370,011373,011374,011375,011376,011378,011379,011381,011383,011386,011387,011389}
# for rnum in 011390
# for rnum in {011391..011403}
# for rnum in {011404,011406,011408,011409}
# for rnum in {011412..011416}
# for rnum in {011417..011423}
# for rnum in {011429,011430}
# for rnum in {011432..011442}
# for rnum in {011443..011447}
# for rnum in {011449,011450}
# for rnum in 011458
# for rnum in {011460,011462,011463}
# for rnum in {011465..011470}
# for rnum in {011471..011473}
# for rnum in {011474,011475,011476,011477,011479,011480,011481}
# for rnum in {011483..011490}
# for rnum in {011491..011496}
# for rnum in {011497..011499}
# for rnum in {011501..011502}
# for rnum in {011504..011507}
# for rnum in {011509..011510}
# for rnum in {011511..011530}
# for rnum in {011531..011539}
# for rnum in 011540
# for rnum in {011541..011544}
# for rnum in {011545..011546}
# for rnum in {011547..011560}
# for rnum in {011561..011571}

# for rnum in {011474..011571}

# decode all
# for rnum in 011328
# for rnum in 011093
# for rnum in 006164
# for rnum in {006164,011093,011328}

# for rnum in 006433
# for rnum in 011571
# for rnum in {011291..011300}

# for rnum in {011301,011302}

#decode 1000
# for rnum in {006164,006223,006288,006351,006420,006546,006565}
# for rnum in {011362,011485,011486,011487,011490}
# for rnum in {011101,011269,011290}
# for rnum in {011117,011207}
# for rnum in {006433,006386}
# for rnum in {006164,006223}
# for rnum in {006328,006465}
# for rnum in 006464
# for rnum in {006218,006549}
# for rnum in 006202
# for rnum in {006223,006330,006351,006433,006546}  # for ctof
# for rnum in 006247  # for ctof
# for rnum in {006255,006336,006354,006383,006399,006472}  # for cnd

# for full run pass1
# for rnum in 006164
# for rnum in 006346
# for rnum in 006420
# for rnum in 006595 

# for rnum in 005823

# for rnum in 006557
# for rnum in 006549
# for rnum in 006202
# for rnum in 006443

# for rnum in 006467
for rnum in 006313

#low lumi
# for rnum in {006323,006373,006374}
# for rnum in {006167,0061678,006169,006170,006265,006322,006371,006446,006447,006448,006561}
# for rnum in {011117,011120,011200,011201,011202,011203,011204,011206,011207}
# for rnum in 011210

# for rnum in $1

# /farm_out/clas12-1/rgb-recana-v20test_11093/rgb-recana-v20test_11093-00096_p0_recon_r011093_f00095.out
# /farm_out/clas12-1/rgb-recana-v20test_11093/rgb-recana-v20test_11093-00347_p0_recon_r011093_f00350.out
# /farm_out/clas12-1/rgb-recana-v20test_11093/rgb-recana-v20test_11093-00093_p0_recon_r011093_f00092.out
# /farm_out/clas12-1/rgb-recana-v20test_11093/rgb-recana-v20test_11093-00095_p0_recon_r011093_f00094.out

do 

# clas12-workflow.py [-h] [--runGroup NAME] [--tag NAME] [--model NAME] [--inputs PATH] [--runs RUN/PATH] [--outDir PATH] [--decDir PATH] [--workDir PATH] [--logDir PATH] [--coatjava PATH] [--clara PATH] [--threads #] [--reconYaml PATH] [--trainYaml PATH] [--claraLogDir PATH] [--phaseSize #] [--mergeSize #] [--trainSize #] [--torus #.#] [--solenoid #.#] [--fileRegex REGEX]                [--config PATH] [--defaults] [--show] [--submit] [--version]

# tag=v17
# clas12-workflow.py --runGroup rgb --tag ${tag} --model ana --inputs /work/clas12/rg-b/production/recon/pass0/${tag}/mon/recon/$rnum --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v17_20191204.yaml --trainYaml /work/clas12/maram/clas_soft/rg-b/clara_4.3.11_coatjava_6b.4.1_grapes_2.4/plugins/grapes/config/train_calib.yaml --submit

# tag=v17
# clas12-workflow.py --runGroup rgb --tag ${tag} --model ana --inputs /work/clas12/rg-b/production/recon/pass0/${tag}/mon/recon/$rnum --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v17_20191204.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_calib.yaml --submit

# tag=v17
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.00[3-9]*" --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara}_${coatjava_cook} --coatjava /group/clas12/packages/clara/${clara}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v17_20191204.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_dst.yaml --submit

# tag=v17
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/cache/clas12/rg-b/data/clas_*$rnum" --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara}_${coatjava_cook} --coatjava /group/clas12/packages/clara/${clara}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v17_20191204.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_trigger.yaml --submit

# tag=v17
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrec --inputs "/cache/clas12/rg-b/data/clas_*$rnum/*.0004*" --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara}_${coatjava_cook} --coatjava /group/clas12/packages/clara/${clara}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v17_20191204.yaml --submit

# tag=v17
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrec --inputs "/cache/clas12/rg-b/data/clas_*$rnum/*.00[1-2]*" --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara}_${coatjava_cook} --coatjava /group/clas12/packages/clara/${clara}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v17_20191204.yaml 

# tag=v18
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum" --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara}_${coatjava_cook} --coatjava /group/clas12/packages/clara/${clara}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v18_20191215.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_calib.yaml --submit

# tag=v18
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs /cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag}  --clara /group/clas12/packages/clara/${clara}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v18_20191215.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_calib.yaml --submit

# tag=v19.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum" --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara}_${coatjava_cook} --coatjava /group/clas12/packages/clara/${clara}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v19.1_20191218.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_calib.yaml --submit

# tag=v19.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs /cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag}  --clara /group/clas12/packages/clara/${clara}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v19.1_20191218.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_calib.yaml --submit

# tag=v19.1.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v19.1.1_20200207.yaml --trainYaml calib --submit

# tag=v19.1.1new
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum" --runs $rnum --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v19.1.1_20200212.yaml --trainYaml calib --postproc --submit

# tag=v19.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs /cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag}  --clara /group/clas12/packages/clara/${clara}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v19.2_20200106.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_calib.yaml --submit

# tag=v19.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/*/*.0004*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019fall_mon_1 --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v19.2_20200106.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_rf.yaml --trainSize 1 --submit

# tag=v19.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*/*.0000*" --runs /work/clas12/rg-b/clas12_cooking_rgb/p --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode}  --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v19.2_20200106.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_rf.yaml --trainSize 1 --submit

# tag=v19.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/cache/clas12/rg-b/data/clas_*$rnum/*" --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v19.2_20200106.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_calib.yaml --trainSize 1 --submit


# tag=v19.2.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*" --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v19.2.1_20200120.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_calib.yaml --trainSize 1 --submit

# tag=v19.2.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/*/*.0004*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2020winter_mon --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v19.2.1_20200120.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_calib.yaml --trainSize 1 --submit

# tag=v19.2.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*.0004*" --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v19.2.1_20200120.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_calib.yaml --submit

# tag=v19.2.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/*/*.0004*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2020winter_mon --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v19.2.2_20200201.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_calib.yaml --submit

# tag=v19.3
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrec --inputs "/mss/clas12/rg-b/data/clas_*/*.0000*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_mon_less --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v19.3_20200211.yaml --postproc --submit

# tag=v21.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*" --runs $rnum --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --workDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.2_20200221.yaml --trainYaml calib --postproc --submit

# tag=v21.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model dec --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*" --runs $rnum --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --submit

# tag=v21.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*" --runs $rnum --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --workDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.2_20200221.yaml --trainYaml calib --postproc --submit

# tag=v21.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs  "/mss/clas12/rg-b/data/clas_*/*.0004*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2020winter_mon_more --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --workDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.2_20200221.yaml --trainYaml calib --postproc --submit

# tag=v21.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/*/*.0000*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_mon_less --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --workDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.2_20200221.yaml --trainYaml calib --postproc --submit

# tag=v21.2.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*" --runs $rnum --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --workDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.2.1_20200307.yaml --trainYaml calib --postproc --submit

# tag=v21.2.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*" --runs $rnum --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --workDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.2.1_20200307.yaml --trainYaml calib --postproc --submit

# tag=v21.3.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrec --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*" --runs $rnum --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --workDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v21.3.1_20200313.yaml --postproc --submit

# tag=v21.3.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrec --inputs "/mss/clas12/rg-b/data/clas_*/*.0000*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019fall_mon_less --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --workDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v21.3.1_20200313.yaml --postproc --submit

# tag=v21.3.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model rec --inputs "/mss/clas12/rg-b/production/decoded/${coatjava_decode}/*/*.0000*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_mon_tmp --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --workDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v21.3.1_20200313.yaml --postproc --submit

# tag=v21.3.1new
# clas12-workflow.py --runGroup rgb --tag ${tag} --model rec --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*" --runs $rnum --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --workDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v21.3.1_20200313.yaml --postproc --submit

# tag=v21.3.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrec --inputs "/mss/clas12/rg-b/data/clas_*/*.0004*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2020winter_mon_more --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --workDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v21.3.2_20200318.yaml --postproc --submit

# tag=v21.4.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.00*" --runs $rnum --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --workDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.4.1_20200302.yaml --trainYaml calib --postproc --submit

# tag=v21.4.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.00*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.4.2_20200331.yaml --trainYaml calib --postproc --submit

# tag=v21.4.3
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.00*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.4.3_20200415.yaml --trainYaml calib --postproc --submit

# tag=v21.4.3
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*.00*" --runs $rnum --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --workDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.4.3_20200415.yaml --trainYaml calib --postproc --submit

# tag=v21.5.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*" --runs $rnum --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --workDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.1_20200317.yaml --trainYaml calib --postproc --submit

# tag=v21.5.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*" --runs $rnum --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --workDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.2_20200320.yaml --trainYaml calib --postproc --submit

# tag=v21.5.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.00*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.2_20200320.yaml --trainYaml calib --postproc --submit

# tag=v21.5.3
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.3_20200414.yaml --trainYaml calib --postproc --submit

# tag=v21.5.4
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.4_20200415.yaml --trainYaml calib --postproc --submit

# tag=v21.5.5
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.00*" --runs $rnum --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --workDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.5_20200417.yaml --trainYaml calib --postproc --submit

# tag=v21.5.6
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*.00*" --runs $rnum --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --workDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.6_20200421.yaml --trainYaml calib --postproc --submit

# tag=v21.5.6new
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/*/*.0000*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_mon_tmp --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.6_20200421.yaml --trainYaml calib --postproc --submit

# tag=v21.5.6
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.00*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.6_20200421.yaml --trainYaml calib --postproc --submit

# tag=v21.5.7
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.00*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.7_20200424.yaml --trainYaml calib --postproc --submit

# tag=v21.5.7
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.7_20200424.yaml --trainYaml calib --postproc --submit

# tag=v21.5.8
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.00*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.8_20200425.yaml --trainYaml calib --postproc --submit

# tag=v21.5.8
# clas12-workflow.py --runGroup rgb --tag ${tag} --model dec --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.00*" --runs $rnum --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_decode}_${coatjava_decode} --submit

# tag=v21.5.8
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.8_20200425.yaml --trainYaml calib --postproc --submit

# tag=v21.5.8
# clas12-workflow.py --runGroup rgb --tag ${tag} --model rec --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*.01[0-4]*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.8_20200425.yaml --postproc --submit

# tag=v21.5.8
# clas12-workflow.py --runGroup rgb --tag ${tag} --model ana --inputs "/volatile/clas12/rg-b/production/recon/pass0/$tag/calib/recon/$rnum/*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.8_20200425.yaml --trainYaml calib --submit

# tag=v21.5.9
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.9_20200428.yaml --trainYaml calib --postproc --submit

# tag=v21.5.9
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.00[0-4]*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.9_20200428.yaml --trainYaml calib --postproc --submit

# tag=v21.5.10
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.00*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.10_20200430.yaml --trainYaml calib --postproc --submit

# tag=v21.5.11
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*.00*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.11_20200506.yaml --trainYaml calib --postproc --submit

# tag=v21.5.12
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*.00*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.12_20200509.yaml --trainYaml calib --postproc --submit

# tag=v21.5.13new
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*.00*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.13_20200512.yaml --trainYaml calib --postproc --submit

# tag=v21.5.13
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.00*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21.5.13_20200512.yaml --trainYaml calib --postproc --submit

# tag=v21.6.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model rec --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/*/*.0004*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_mon_more --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --workDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v21.6.1_20200406.yaml --postproc --submit

# tag=v21.6.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model rec --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/*/*.0000*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_mon_tmp --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --workDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v21.6.2_20200416.yaml --postproc --submit

# tag=v21.6.3
# clas12-workflow.py --runGroup rgb --tag ${tag} --model rec --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/*/*.0000*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2020winter_mon_less --outDir /cache/clas12/rg-b/production/recon/pass0/${tag} --workDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v21.6.3_20200418.yaml --postproc --submit

# tag=v21.7.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model rec --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/*/*.0000*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_mon_less --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v21.7.1_20200424.yaml --postproc --submit

# tag=v21.7.1new
# clas12-workflow.py --runGroup rgb --tag ${tag} --model rec --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/*/*.0004*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_mon_tmp --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v21.7.1_20200425.yaml --postproc --submit

# tag=v21.7.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model dec --inputs "/mss/clas12/rg-b/data/clas_*/*.0005*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_mon_more --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_decode}_${coatjava_decode} --submit

# tag=v21.7.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model dec --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.00*" --runs $rnum --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_decode}_${coatjava_decode} --submit

# tag=v21.7.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model rec --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/*/*.0005*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_mon_more --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v21.7.2_20200501.yaml --postproc --submit

# tag=v21.7.3
# clas12-workflow.py --runGroup rgb --tag ${tag} --model rec --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/*/*.0004*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_mon_tmp --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v21.7.3_20200504.yaml --postproc --submit

# tag=v21.7.4
# clas12-workflow.py --runGroup rgb --tag ${tag} --model rec --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/*/*.0004*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_mon_tmp --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v21.7.4_20200506.yaml --postproc --submit

# tag=v21.7.5
# clas12-workflow.py --runGroup rgb --tag ${tag} --model rec --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/*/*.0000*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_mon_tmp --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v21.7.5_20200511.yaml --postproc --submit

# tag=v21.8.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model rec --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/*/*.0004*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_mon_more --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v21.8.1_20200522.yaml --postproc --submit

# tag=v21.8.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model rec --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/*/*.0004*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_mon_tmp --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v21.8.2_20200526.yaml --postproc --submit

# tag=v22.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.000*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_dst_pass0v22.1_20200417.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_dst.yaml --postproc --submit

# tag=v22.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_dst_pass0v22.2_20200417.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_dst.yaml --postproc --submit

# tag=v22.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/*/*.000*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag}  --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_dst_pass0v22.2_20200417.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_dst.yaml --postproc --submit

# tag=v22.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model dec --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.00*" --runs $rnum --decDir /volatile/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_decode}_${coatjava_decode} --submit

# tag=v22.3
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/volatile/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*.00*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag}  --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v22.3_20200429.yaml --trainYaml calib --postproc --submit

# tag=v22.3
# clas12-workflow.py --runGroup rgb --tag ${tag} --model ana --inputs "/volatile/clas12/rg-b/production/recon/pass0/${tag}/calib/recon/$rnum/*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag}  --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v22.3_20200429.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_dst_shrink.yaml --submit

# tag=v22.4
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/volatile/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*.00[0-4]*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag}  --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v22.4_20200506.yaml --trainYaml calib --postproc --submit

# tag=v22.5
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decmrg --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.00*" --runs $rnum --decDir /volatile/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_decode}_${coatjava_decode} --mergeSize 5 --submit

# tag=v23.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.00[0-4]*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /volatile/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v23.1_20200515.yaml --trainYaml calib --postproc  --submit

# tag=v23.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model ana --inputs "/volatile/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v23.1_20200515.yaml --trainYaml calib  --submit

# tag=v23.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/volatile/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag}  --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_dst_pass0v23.2_20200515.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_dst.yaml --postproc --phaseSize 1 --submit

# tag=v23.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model ana --inputs "/volatile/clas12/rg-b/production/recon/pass0/${tag}/dst/recon/$rnum/*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag}new  --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_dst_pass0v23.2_20200515.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_dst.yaml --phaseSize 1 --submit

# tag=v23.2m
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/volatile/clas12/rg-b/production/decoded/${coatjava_decode}m/$rnum/*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag}  --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_dst_pass0v23.2_20200515.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_dst.yaml --postproc --phaseSize 1 --submit

# tag=v23.3
# clas12-workflow.py --runGroup rgb --tag ${tag} --model dec --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.00[5-9]*" --runs $rnum --decDir /volatile/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_decode}_${coatjava_decode} --submit

# tag=v23.3
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs "/volatile/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum/*.0*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag}  --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v23.3_20200526.yaml --trainYaml calib --postproc --submit

# tag=v23.3
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-k/data/clas_*$rnum/*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /volatile/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v23.3_20200526.yaml --trainYaml calib --postproc  --submit

# tag=v23.3new
# clas12-workflow.py --runGroup rgk --tag ${tag} --model ana --inputs "/volatile/clas12/rg-b/production/recon/pass0/v23.3/calib/recon/$rnum/" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v23.3_20200526.yaml --trainYaml calib  --submit

# tag=v23.4
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs /cache/clas12/rg-b/production/decoded/${coatjava_decode}/$rnum --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag}  --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_dst_pass0v23.4_20200610.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_dst.yaml --postproc --submit

# tag=v23.4new
# clas12-workflow.py --runGroup rgb --tag ${tag} --model ana --inputs /volatile/clas12/rg-b/production/recon/pass0/v23.4/dst/recon/$rnum --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag}  --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_dst_pass0v23.4_20200610.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_dst.yaml --submit

# tag=v24.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrec --inputs "/mss/clas12/rg-b/data/clas_*/*.0004*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019fall_mon_more --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /volatile/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v24.1_20200619.yaml --postproc --submit

# tag=v24.2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*/*.00*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_tmp --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /volatile/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v24.2_20200709.yaml --trainYaml calib --postproc --submit

# tag=v24.3
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs /mss/clas12/rg-b/data --runs "011286-011300" --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /volatile/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_dst_pass0v24.3_20200709.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_dst.yaml --postproc --submit

# tag=v24.4
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs /volatile/clas12/rg-b/production/decoded/${coatjava_decode} --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_tmp --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v24.4_20200821.yaml --trainYaml calib --postproc --submit

tag=v24.5
clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/*/*evio.00*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_tmp --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --decDir /volatile/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v24.5_20200902.yaml --trainYaml calib --postproc --submit

# tag=v24.5
# clas12-workflow.py --runGroup rgb --tag ${tag} --model recana --inputs /volatile/clas12/rg-b/production/decoded/${coatjava_decode} --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_tmp --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v24.5_20200902.yaml --trainYaml calib --postproc --submit

# tag=pass1v0
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decmrg --inputs /mss/clas12/rg-b/data --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_decode2 --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_decode}_${coatjava_decode} --mergeSize 5 --phaseSize 1

# tag=pass1v0
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decmrg --inputs "/mss/clas12/rg-b/data/clas_006467/*.0[1-2]*" --runs 006467 --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_decode}_${coatjava_decode} --mergeSize 5 --phaseSize 1 --submit

# tag=pass1v0
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decmrg --inputs "/mss/clas12/rg-b/data/clas_006467/*.0[1-2]*" --runs 006467 --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_decode}_${coatjava_decode} --mergeSize 5 --phaseSize 1 --submit

# tag=pass1v0
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decmrg --inputs "/mss/clas12/rg-b/data/clas_006328/*.02*" --runs 006328 --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_decode}_${coatjava_decode} --mergeSize 5 --submit

# pass=pass1
# tag=v0

# clas12-workflow.py --runGroup rgb --tag $pass$tag --model decmrgrecana --inputs /mss/clas12/rg-b/data --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_cook10 --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --outDir /cache/clas12/rg-b/production/recon/spring2019/torus-1/$pass/$tag --workDir /volatile/clas12/rg-b/production/recon/spring2019/torus-1/$pass/$tag/work --logDir /volatile/clas12/rg-b/production/recon/spring2019/torus-1/$pass/$tag/log --trainDir /volatile/clas12/rg-b/production/recon/spring2019/torus-1/$pass/$tag --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_dst_pass1v0_20200610.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_dst.yaml --mergeSize 5 --postproc --submit

# clas12-workflow.py --runGroup rgb --tag $pass$tag --model recana --inputs /cache/clas12/rg-b/production/decoded/${coatjava_decode} --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_cook0 --outDir /cache/clas12/rg-b/production/recon/spring2019/torus-1/$pass/$tag --workDir /volatile/clas12/rg-b/production/recon/spring2019/torus-1/$pass/work_$tag --trainDir /volatile/clas12/rg-b/production/recon/spring2019/torus-1/$pass/$tag --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_dst_pass1v0_20200610.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_dst.yaml --postproc --submit

# clas12-workflow.py --runGroup rgb --tag $pass$tag --model decmrgrecana --inputs /mss/clas12/rg-b/data --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_cook5 --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --outDir /cache/clas12/rg-b/production/recon/$pass/$tag --workDir /volatile/clas12/rg-b/production/recon/$pass/work_$tag --trainDir /volatile/clas12/rg-b/production/recon/$pass/$tag --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_dst_pass1v0_20200610.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_dst.yaml --mergeSize 5 --postproc --submit

# clas12-workflow.py --runGroup rgb --tag tmptmp --model decmrgrec --inputs "/mss/clas12/rg-b/data/clas_006313/*evio.0111*" --runs 006313 --outDir /volatile/clas12/rg-b/production/recon/tmp --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_dst_pass1v0_20200610.yaml --mergeSize 5 --postproc --submit

# clas12-workflow.py --runGroup rgb --tag tmp --model decmrgrec --inputs "/mss/clas12/rg-b/data/clas_006467/*evio.0023[5-9]*" --runs 006467 --outDir /volatile/clas12/rg-b/production/recon/tmp --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook}  --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_dst_pass1v0_20200610.yaml --mergeSize 5 --postproc --submit

# clas12-workflow.py --runGroup rgb --tag $pass$tag --model recana --inputs /cache/clas12/rg-b/production/decoded/${coatjava_decode} --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_cook4 --outDir /cache/clas12/rg-b/production/recon/$pass/$tag --workDir /volatile/clas12/rg-b/production/recon/$pass/work_$tag --trainDir /volatile/clas12/rg-b/production/recon/$pass/$tag --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_dst_pass1v0_20200610.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_dst.yaml --postproc --submit

# clas12-workflow.py --runGroup rgb --tag $pass$tag --model rec --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/006515/*evio.0[1-2]*" --runs 006515 --outDir /cache/clas12/rg-b/production/recon/$pass/$tag --workDir /volatile/clas12/rg-b/production/recon/$pass/work_$tag --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_dst_pass1v0_20200610.yaml --postproc --submit

# clas12-workflow.py --runGroup rgb --tag tmp --model ana --inputs /cache/clas12/rg-b/production/recon/spring2019/torus-1/$pass/$tag/dst/recon --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_cook9 --outDir /volatile/clas12/rg-b/production/recon/spring2019/torus-1/$pass/$tag --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_dst_pass1v0_20200610.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_dst.yaml --submit

# clas12-workflow.py --runGroup rgb --tag tmp --model ana --inputs /cache/clas12/rg-b/production/recon/$pass/$tag/dst/recon --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_tmp --outDir /volatile/clas12/rg-b/production/recon/tmp --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_dst_pass1v0_20200610.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_dst.yaml --submit

# clas12-workflow.py --runGroup rgb --tag tmp --model ana --inputs /cache/clas12/rg-b/production/recon/spring2019/torus-1/$pass/$tag/dst/recon/$rnum --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/test --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_dst_pass1v0_20200610.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_dst.yaml --submit

# clas12-workflow.py --runGroup rgb --tag tmp --model decmrg --inputs /mss/clas12/rg-b/data --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_tmp --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_decode}_${coatjava_decode} --mergeSize 5 --submit

# tag=decodetest1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decmrg --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.0000*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --mergeSize 4  --submit

# tag=decodetest2
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decmrgrec --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.0000*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --mergeSize 4  --submit

# tag=v19.3
# clas12-workflow.py --runGroup rgb --tag ${tag} --model rec --inputs "/cache/clas12/rg-b/production/decoded/${coatjava_decode}/*/*.0004*" --runs /work/clas12/rg-b/clas12_cooking_rgb/runlist_2019spring_mon --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v19.3_20200205.yaml --submit

# tag=test6b.5.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.0004*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21_20200204.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_calib.yaml --submit

# tag=testtrain6b.5.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.0004*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21_20200204.yaml --trainYaml calib --submit

# tag=testtrainagain6b.5.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.0004*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v21_20200211.yaml --trainYaml calib --postproc --submit

# tag=testtrigger6b.5.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model ana --inputs "/volatile/clas12/rg-b/production/recon/pass0/v19.3/mon/recon/*/*.0004*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /work/clas12/users/baltzell/clara-grapes-test_6b.5.1 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v21_20200211.yaml --trainYaml trigger --submit

# tag=testtrigger6b.5.1
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum/*.0004*" --runs $rnum --outDir /volatile/clas12/rg-b/production/recon/pass0/${tag} --clara /work/clas12/users/baltzell/clara-grapes-test_6b.5.1 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v21_20200211.yaml --trainYaml trigger --postproc --submit

# tag=v20
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrec --inputs "/cache/clas12/rg-b/data/clas_*$rnum/*.0004*" --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v20_20200108.yaml --submit

# tag=v20
# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrec --inputs "/mss/clas12/rg-b/data/clas_*$rnum" --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava_decode} --clara /group/clas12/packages/clara/${clara_cook}_${coatjava_cook} --coatjava /group/clas12/packages/clara/${clara_decode}_${coatjava_decode}/plugins/clas12 --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v20_20200108.yaml --submit

# ===========================

# clas12-workflow.py --runGroup rgb --tag ${tag} --model rec --inputs /home/clas12-1/files --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara}_${coatjava} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v17_20191204.yaml --submit

# clas12-workflow.py --runGroup rgb --tag ${tag} --model rec --inputs "/cache/clas12/rg-b/production/decoded/${coatjava}/$rnum/*.0004*" --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara}_${coatjava} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v17_20191204.yaml --submit

# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrec --inputs /mss/clas12/rg-b/data/clas_*$rnum --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava} --clara /group/clas12/packages/clara/${clara}_${coatjava} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v17_20191204.yaml --solenoid -1.0 --torus 1.0 --submit

# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrec --inputs "/cache/clas12/rg-b/data/clas_*$rnum/*.0004*" --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava} --clara /group/clas12/packages/clara/${clara}_${coatjava} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v17_20191204.yaml --submit

# clas12-workflow.py --runGroup rgb --tag ${tag} --model ana --inputs /work/clas12/rg-b/production/recon/pass0/${tag}/calib/unfiltered/$rnum --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara}_${coatjava} --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_calib.yaml --submit

# clas12-workflow.py --runGroup rgb --tag ${tag} --model ana --inputs /work/clas12/rg-b/production/recon/pass0/${tag}/recon/$rnum --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --clara /group/clas12/packages/clara/${clara}_${coatjava} --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_trigger.yaml --submit

# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum" --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava} --clara /group/clas12/packages/clara/${clara}_${coatjava} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_calib_pass0v17_20191204.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_calib.yaml --solenoid -1.0 --torus 1.0 --submit

# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/mss/clas12/rg-b/data/clas_*$rnum" --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava} --clara /group/clas12/packages/clara/${clara}_${coatjava} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v17_20191204.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_calib.yaml --solenoid -1.0 --torus 1.0 --submit

# clas12-workflow.py --runGroup rgb --tag ${tag} --model decrecana --inputs "/cache/clas12/rg-b/data/clas_*$rnum" --runs $rnum --outDir /work/clas12/rg-b/production/recon/pass0/${tag} --decDir /cache/clas12/rg-b/production/decoded/${coatjava} --clara /group/clas12/packages/clara/${clara}_${coatjava} --reconYaml /work/clas12/rg-b/clas12_cooking_rgb/rgb_mon_pass0v17_20191204.yaml --trainYaml /work/clas12/rg-b/clas12_cooking_rgb/train_calib.yaml --submit


# CRITICAL [CLAS12Jobs     ] Configuration conflicts with /cache/clas12/rg-b/production/decoded/6b.4.0/config.json

# If you don't specify --coatjava, it will use the one in --clara.

# --workDir /work/clas12/rg-b/clas12_clara${clara}_coatjava${coatjava} 

# clas12-workflow.py --runGroup rga --model dec --runs 4013,4014 --inputs /mss/clas12/rg-a/data --outDir /volatile/clas12/rg-a/test

# get 0004 file on cache correct, but output name as 0000
# possible fix from Nathan, i.e. move the 4 right by one character to be inside the parentheses
# Or, more generally, probably "\.(0*4\d)$" should give files 40-49 regardless of how many left-buffered zeroes there are.

# swif import -file jobs/rgb-decode-${coatjava}_R${rnum}x1.json
# swif import -slurm -file jobs/rgb-decode-${coatjava}_R${rnum}x1.json

# swif run -workflow rgb-decode-${coatjava}_R${rnum}x1

# ./scripts/swif-status.py --retry --workflow rgb-decode-${coatjava}_R${rnum}x1_x1200

# do  echo $xx;
done