io-services:
  reader:
    class: org.jlab.jnp.grapes.io.HipoFrameReader
    name: HipoFrameReader
  writer:
    class: org.jlab.jnp.grapes.io.HipoFrameWriter
    name: HipoFrameWriter
services:
#################################################### JPSI/TCS
  - class: org.jlab.jnp.grapes.services.JpsiTcsWagon
    name: JPSITCS
#################################################### nDVCS
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: nDVCSQ1
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: nDVCSQ2
#################################################### eDeut
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: eDeutQ1
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: eDeutQ2
#################################################### nSidisCut
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: nSidisCut
#################################################### TWO    
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: TWO1
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: TWO2
configuration:
  custom-names:
    1: jpsi 
    2: ndvcscut
    3: edeutcut
    4: nsidis
    5: two    
  services:
#################################################### JPSI/TCS
    JPSITCS:
      id: 1
#################################################### nDVCS
    nDVCSQ1:
      id: 2
      forward: 11:Xn
      beamEnergy: 10.4096
      targetPDG: 2112
      electron: Q2>0.9
    nDVCSQ2:
      id: 2
      forward: 11:2212:Xn
      beamEnergy: 10.4096
      targetPDG: 2112
      electron: Q2>0.9
#################################################### eDeut
    eDeutQ1:
      id: 3
      forward: 11:45:X+:X-:Xn
      beamEnergy: 10.4096
      targetPDG: 45
      electron: Q2>0.9
    eDeutQ2:
      id: 3
      forward: 11:X+:X-:Xn
      central: 45:X+:X-:Xn
      beamEnergy: 10.4096
      targetPDG: 45
      electron: Q2>0.9      
#################################################### nSidis
    nSidisCut:
      id: 4
      forward: 11:X+:X-:Xn
      beamEnergy: 10.4096
      targetPDG: 2112 
      electron: Q2>1.0 && W>2 && p>2 && vz>-25 && vz<20
#################################################### Two
    TWO1:
      id: 5
      filter: 321:321:X+:X-:Xn
    TWO2:
      id: 5
      filter: 2212:2212:X+:X-:Xn      
      
mime-types:
  - binary/data-hipo-frame
