io-services:
  reader:
    class: org.jlab.jnp.grapes.io.HipoFrameReader
    name: HipoFrameReader
  writer:
    class: org.jlab.jnp.grapes.io.HipoFrameWriter
    name: HipoFrameWriter
services:
#################################################### JPSI/TCS
  - class: org.jlab.jnp.grapes.services.JpsiTcsWagon
    name: JPSITCS
#################################################### nDVCS
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: nDVCS1
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: nDVCS2
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: nDVCS3
#################################################### eDeut
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: eDeut1
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: eDeut2
#################################################### INCLUSIVE
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: INCLUSIVE1
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: INCLUSIVE2
#################################################### TWO    
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: TWO1
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: TWO2    
configuration:
  custom-names:
    1: jpsi 
    2: ndvcs
    3: edeut
    4: inc
    5: two    
  services:
#################################################### JPSI/TCS
    JPSITCS:
      id: 1
#################################################### nDVCS
    nDVCS1:
      id: 2
      forward: 11:Xn
      tagger: Xn
      central: 1n:Xn:X+:X-
    nDVCS2:
      id: 2
      forward: 11:2212:Xn
      tagger: Xn
      central: Xn
    nDVCS3:
      id: 2
      forward: 11:Xn
      tagger: Xn
      central: 2212:Xn
#################################################### eDeut
    eDeut1:
      id: 3
      forward: 11:45:X+:X-:Xn
      tagger: X+:X-:Xn
      central: X+:X-:Xn
    eDeut2:
      id: 3
      forward: 11:X+:X-:Xn
      tagger: X+:X-:Xn
      central: 45:X+:X-:Xn
#################################################### INCLUSIVE
    INCLUSIVE1:
      id: 4
      forward: 11:X+:X-:Xn
      tagger: X+:X-:Xn
      central: X+:X-:Xn
    INCLUSIVE2:
      id: 4
      forward: -11:X+:X-:Xn
      tagger: X+:X-:Xn
      central: X+:X-:Xn
#################################################### Two
    TWO1:
      id: 5
      filter: 321:321:X+:X-:Xn
    TWO2:
      id: 5
      filter: 2212:2212:X+:X-:Xn      
      
mime-types:
  - binary/data-hipo-frame
